/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:0a33b091-e4f4-499a-9955-8e1cdff5809d",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_aDcYJidFr",
    "aws_user_pools_web_client_id": "4iv29v6qcmj5dhgn5cebe5ffmf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "demo-table",
            "region": "eu-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "customer-dashcam-videos",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://6da6r6k6ovdenjnpuwa25pw5ue.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vlm6nevfcbdtpmv4moycsepx24"
};


export default awsmobile;
